export const zh_cn = {
  startsWith: '开头为',
  contains: '包含',
  notContains: '不包含',
  endsWith: '结尾为',
  equals: '等于',
  notEquals: '不等于',
  noFilter: '无过滤器',
  lt: '小于',
  lte: '小于或等于',
  gt: '大于',
  gte: '大于或等于',
  dateIs: '为',
  dateIsNot: '不为',
  dateBefore: '晚于',
  dateAfter: '早于',
  clear: '清除',
  apply: '应用',
  matchAll: '匹配所有',
  matchAny: '匹配任何',
  addRule: '添加规则',
  removeRule: '删除规则',
  accept: '接受',
  reject: '取消',
  choose: '选择',
  upload: '上传',
  cancel: '取消',
  completed: '完成',
  pending: '等待',
  fileSizeTypes: ['B', 'KB', 'MB', 'GB', 'TB', 'PB', 'EB', 'ZB', 'YB'],
  dayNames: ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
  dayNamesShort: ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'],
  dayNamesMin: ['Su', 'Mo', 'Tu', 'We', 'Th', 'Fr', 'Sa'],
  monthNames: [
    'January',
    'February',
    'March',
    'April',
    'May',
    'June',
    'July',
    'August',
    'September',
    'October',
    'November',
    'December',
  ],
  monthNamesShort: [
    'Jan',
    'Feb',
    'Mar',
    'Apr',
    'May',
    'Jun',
    'Jul',
    'Aug',
    'Sep',
    'Oct',
    'Nov',
    'Dec',
  ],
  chooseYear: '选择年份',
  chooseMonth: '选择月份',
  chooseDate: '选择日期',
  prevDecade: '前十年',
  nextDecade: '下十年',
  prevYear: '前一年',
  nextYear: '下一年',
  prevMonth: '前个月',
  nextMonth: '下个月',
  prevHour: '前一小时',
  nextHour: '下一小时',
  prevMinute: '前一分钟',
  nextMinute: '下一分钟',
  prevSecond: '前一秒',
  nextSecond: '下一秒',
  am: '上午',
  pm: '下午',
  today: '今天',
  weekHeader: '',
  firstDayOfWeek: '',
  showMonthAfterYear: '',
  dateFormat: 'mm/dd/yy',
  weak: '弱',
  medium: '中等',
  strong: '强',
  passwordPrompt: '输入密码',
  searchMessage: '{0} 结果可用',
  selectionMessage: '{0} 个已选择的项目',
  emptySelectionMessage: '未选择项目',
  emptySearchMessage: '未找到结果',
  fileChosenMessage: '{0} 个文件',
  noFileChosenMessage: '未选择文件',
  emptyMessage: '无可用选项',
  'aria.trueLabel': '真',
  'aria.falseLabel': '假',
  'aria.nullLabel': '未选中',
  'aria.star': '1 星',
  'aria.stars': '{star} 星',
  'aria.selectAll': '已选择所有项目',
  'aria.unselectAll': '未选中所有项目',
  'aria.close': '关闭',
  'aria.previous': '前一个',
  'aria.next': '下一个',
  'aria.navigation': '导航',
  'aria.scrollTop': '滚动到顶部',
  'aria.moveTop': '上移到顶部',
  'aria.moveUp': '上移',
  'aria.moveDown': '下移',
  'aria.moveBottom': '下移到底部',
  'aria.moveToTarget': '移动到目标位置',
  'aria.moveToSource': '移动到源位置',
  'aria.moveAllToSource': '全部移动到源位置',
  'aria.pageLable': '第 {page} 页',
  'aria.firstPageLabel': '第一页',
  'aria.lastPageLabel': '最后一页',
  'aria.nextPageLabel': '下一页',
  'aria.prevPageLabel': '上一页',
  'aria.rowsPerPageLabel': '每页行数',
  'aria.jumpToPageDropdownLabel': '跳转至页面下拉列表',
  'aria.jumpToPageInputLabel': '跳转至页面输入',
  'aria.selectRow': '选中行',
  'aria.unselectRow': '未选中行',
  'aria.expandRow': '展开行',
  'aria.collapseRow': '折叠行',
  'aria.showFilterMenu': '（显示过滤器）菜单',
  'aria.hideFilterMenu': '（隐藏过滤器）菜单',
  'aria.filterOperator': '过滤器运算符',
  'aria.filterConstraint': '筛选约束',
  'aria.editRow': '编辑行',
  'aria.saveEdit': '保存编辑',
  'aria.cancelEdit': '取消编辑',
  'aria.listView': '列表视图',
  'aria.gridView': '网格视图',
  'aria.slide': '滑动',
  'aria.slideNumber': '{slideNumber}',
  'aria.zoomImage': '缩放图像',
  'aria.zoomIn': '放大',
  'aria.zoomOut': '缩小',
  'aria.rotateRight': ' 向右旋转',
  'aria.rotateLeft': '向左旋转',
}

export default zh_cn
